version: "3.7"

volumes:
  postgres_data:

services:
  db:
    restart: always
    image: "postgres:12.0-alpine"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./dockers/envs/.env.dev.db


  web:
    build: .
    command:  python module_pay/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - db