# Generated by Django 3.0.7 on 2020-06-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20200619_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='time_confirmed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время подтверждения'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='time_transaction',
            field=models.DateTimeField(null=True, verbose_name='Время транзакции'),
        ),
    ]
